version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: base-datos-Odoo
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: